name: "xihe-statistics"
http_port: 8080
duration: 180

pgsql:
  host: "127.0.0.1"
  port: "5432"
  user: "xihe"
  db_name: "xihe-statistics"
  password: "password@1"

mq:
  address: "47.106.222.191:10004"
  max_retry: 5
  topics:
    statistics: "xihe-statistics"