name: "xihe-statistics"
http_port: 8080
duration: 180

mongodb:
  db_name: "xihe"
  db_conn: "mongodb://xiheAdmin:Password11@127.0.0.1:27017/xihe?timeoutMS=5000"
  collections:
    d0: "d0"
    bigmodel: "bigmodelRecord"
    repo: "repoRecord"
    d1: "d1"
    d2: "d2"
